name: Publish DockerHub

on:
  push:
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to DockerHub
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: blockchainetl/polygon-etl
          workdir: cli
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
