name: Publish to PyPI and TestPyPI

on:
  push:
    tags:
       - '*'

jobs:
  build-n-publish:
    name: Build and publish to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.12"
      - name: Build a binary wheel and a source tarball
        run: cd cli && python setup.py sdist
      - name: Publish distribution to Test PyPI
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: cli/dist/
      - name: Publish distribution to PyPI
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}
          packages_dir: cli/dist/
